### ISSUE TITLE
T07_Elasticsearch_Hadoop_Integration : Error occurred executing hive query: Error running query: java.lang.NullPointerException

### ISSUE THREAD

**Issue by JeffreyZZ** [hortonworks/hadoop-tutorials#51]
I'm new to this tool and got NullPointerException when using 2.1.1 version with the sandbox. Any step that I missed?

[12/Sep/2015 17:39:16 +0000] dbms         ERROR    Bad status for request TExecuteStatementReq(confOverlay={}, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(secret='\xf9\x10\x8a=\xdd\xc8H*\x81I\xc7\xd8\xd7\x07\x92\x94', guid='\xf8\x95,\t\x91}Kl\xa0/g\xfdg\xa7S\xec')), runAsync=False, statement='ADD FILE hdfs://sandbox.hortonworks.com:8020/user/hue/elasticsearch-hadoop-2.1.1.jar'):
TExecuteStatementResp(status=TStatus(errorCode=0, errorMessage='Error running query: java.lang.NullPointerException', sqlState=None, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error running query: java.lang.NullPointerException:15:14', 'org.apache.hive.service.cli.operation.HiveCommandOperation:runInternal:HiveCommandOperation.java:123', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:257', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:388', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:369', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:261', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:486', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:285', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1145', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:615', 'java.lang.Thread:run:Thread.java:745', '*java.lang.NullPointerException:null:19:4', 'org.apache.ranger.authorization.hive.authorizer.RangerHiveAuthorizer:checkPrivileges:RangerHiveAuthorizer.java:244', 'org.apache.hadoop.hive.ql.processors.CommandUtil:authorizeCommandThrowEx:CommandUtil.java:86', 'org.apache.hadoop.hive.ql.processors.CommandUtil:authorizeCommand:CommandUtil.java:59', 'org.apache.hadoop.hive.ql.processors.AddResourceProcessor:run:AddResourceProcessor.java:59', 'org.apache.hive.service.cli.operation.HiveCommandOperation:runInternal:HiveCommandOperation.java:105'], statusCode=3), operationHandle=None)
Traceback (most recent call last):

**Comment by mneethiraj** [comment]
This issue is fixed in Dal-M10. BUG-42771

**Comment by JeffreyZZ** [comment]
@mneethiraj  Thanks for the reply. What is Dal-M10? Is it a fix with Sandbox or Elasticsearch-hadoop plugin? Much appreciated if you can provide more details about this fix, so I could figure out how to work around this issue.

**Comment by mneethiraj** [comment]
@JeffreyZZ . Please ignore the reference to Dal-M10 (it is a Hortonworks codename for a release). The issue you hit is RANGER-622 (https://issues.apache.org/jira/browse/RANGER-622). Fix for this issue has been committed in Apache few weeks back.

To update your sandbox with this fix, you would have to build the latest ranger-0.5 branch and copy hive-agent/target/ranger-hive-plugin-0.5.0.jar to your sandbox at /usr/hdp/2.3.*/hive/lib/ranger-hive-plugin*.jar; and restart HiveServer2.

If this is not feasible, I guess you will have to use SQLStdAuth as the authorizer for Hive (in Ambari).

**Comment by JeffreyZZ** [comment]
@mneethiraj  Thank you so much! This is very helpful.
